import {SubjectToTake} from '@root/features/SubjectsToTake/types';

export const exampleToTake: SubjectToTake[] = [
  {
    disciplina: 'Desenho Técnico I',
    codigo: 'IME03-00738',
    ramificacao: '79',
    periodo: '3',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Física Teórica e Experimental IV',
    codigo: 'FIS04-05212',
    ramificacao: '474',
    periodo: '4',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Conversão Eletromecânica de Energia III',
    codigo: 'FEN04-05153',
    ramificacao: '479',
    periodo: '5',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Eletromagnetismo III',
    codigo: 'FEN04-05105',
    ramificacao: '479',
    periodo: '5',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Análise de Sistemas Físicos I',
    codigo: 'FEN04-05253',
    ramificacao: '479',
    periodo: '6',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Circuitos Elétricos IV',
    codigo: 'FEN04-05222',
    ramificacao: '479',
    periodo: '6',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Eletrônica II',
    codigo: 'FEN05-01840',
    ramificacao: '474',
    periodo: '6',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Materiais Elétricos e Magnéticos',
    codigo: 'FEN04-05197',
    ramificacao: '479',
    periodo: '6',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Controle e Servomecanismos III',
    codigo: 'FEN05-05025',
    ramificacao: '479',
    periodo: '7',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Fundamentos de Computadores Digitais I',
    codigo: 'FEN06-03787',
    ramificacao: '479',
    periodo: '7',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Instalações de Ambiente Computacional',
    codigo: 'FEN06-03860',
    ramificacao: '479',
    periodo: '7',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Princípios de Telecomunicações III',
    codigo: 'FEN05-04975',
    ramificacao: '479',
    periodo: '7',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Arquitetura de Computadores I',
    codigo: 'FEN06-04119',
    ramificacao: '479',
    periodo: '8',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Microcomputadores e Microprocessadores I',
    codigo: 'FEN06-04192',
    ramificacao: '479',
    periodo: '8',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Arquitetura de Sistemas Operacionais',
    codigo: 'FEN06-04664',
    ramificacao: '479',
    periodo: '9',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Estágio Supervisionado XI - A',
    codigo: 'FEN06-05038',
    ramificacao: '479',
    periodo: '9',
    conflito: true,
    trava: 160,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Projeto de Ambiente Computacional',
    codigo: 'FEN06-04832',
    ramificacao: '479',
    periodo: '9',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Projeto de Graduação XI - A',
    codigo: 'FEN06-04578',
    ramificacao: '479',
    periodo: '9',
    conflito: true,
    trava: 170,
    prereq: false,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Teleprocessamento e Redes de Computadores',
    codigo: 'FEN06-04718',
    ramificacao: '479',
    periodo: '9',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Teoria de Compiladores',
    codigo: 'FEN06-04516',
    ramificacao: '479',
    periodo: '9',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Controle de Processos por Computador',
    codigo: 'FEN06-05080',
    ramificacao: '479',
    periodo: '10',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Engenharia de Sistemas C',
    codigo: 'FEN06-04386',
    ramificacao: '479',
    periodo: '10',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Engenharia na Sociedade II',
    codigo: 'FEN02-01390',
    ramificacao: '479',
    periodo: '10',
    conflito: false,
    trava: 170,
    prereq: false,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Projeto de Graduação XI - B',
    codigo: 'FEN06-04635',
    ramificacao: '479',
    periodo: '10',
    conflito: true,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Obrigatórias',
  },
  {
    disciplina: 'Tópicos Especiais em Sistemas e Computação A',
    codigo: 'FEN06-04889',
    ramificacao: '479',
    grupo: '1',
    periodo: '10',
    conflito: false,
    trava: 170,
    prereq: false,
    type: 'Disciplinas Eletivas Restritas',
  },
  {
    disciplina: 'Tópicos Especiais em Sistemas e Computação B',
    codigo: 'FEN06-04939',
    ramificacao: '479',
    grupo: '1',
    periodo: '10',
    conflito: false,
    trava: 170,
    prereq: false,
    type: 'Disciplinas Eletivas Restritas',
  },
  {
    disciplina: 'Análise de Sistema de Potência I',
    codigo: 'FEN04-00272',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Análise Estrutural I',
    codigo: 'FEN01-00163',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Análise Estrutural II',
    codigo: 'FEN01-00334',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Antenas e Propagação II',
    codigo: 'FEN05-00298',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Auditoria de Sistema de Gestão',
    codigo: 'FEN09-08549',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Edificações I',
    codigo: 'FEN02-00547',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Edificações II',
    codigo: 'FEN02-00701',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Engenharia de Custos',
    codigo: 'FEN02-00879',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Engenharia e Gestão de Processos de Negócios',
    codigo: 'FEN09-14745',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Estatística Não - Paramétrica Aplicada',
    codigo: 'FEN09-14742',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Física Teórica e Experimental IV',
    codigo: 'FIS04-05212',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Geometria Diferencial',
    codigo: 'IME02-07027',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Gestão de Recursos Hídricos',
    codigo: 'FEN07-12759',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Gestão do Conhecimento',
    codigo: 'FEN09-14738',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Logística e Gestão da Cadeia de Suprimentos',
    codigo: 'FEN09-14747',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Materiais de Construção Mecânica I',
    codigo: 'FEN03-03424',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Mecânica Aplicada I',
    codigo: 'FEN03-03598',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Mecânica dos Fluidos V',
    codigo: 'FEN03-06595',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Modelos Probabilísticos em Telecomunicações',
    codigo: 'FEN05-05114',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Planejamento e Controle de Obras',
    codigo: 'FEN02-02500',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Portos I',
    codigo: 'FEN02-03807',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Portos II',
    codigo: 'FEN02-03879',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Princípios de Telecomunicações II',
    codigo: 'FEN05-03774',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Projeto do Empreendimento',
    codigo: 'FEN09-07342',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Resistencia dos Materiais II',
    codigo: 'FEN01-03866',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Sistemas de Transportes I',
    codigo: 'FEN02-02925',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina:
      'Tópicos Especiais Aplicados à Engenharia Ambiental e Sanitária I',
    codigo: 'FEN07-12780',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Tópicos Especiais em Eletrônica',
    codigo: 'FEN05-04763',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Tópicos Especiais em Métodos Quantitativos',
    codigo: 'FEN09-07780',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: true,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Tópicos Especiais em Planejamento e Controle da Produção',
    codigo: 'FEN09-14732',
    periodo: '-',
    conflito: false,
    trava: 0,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
  {
    disciplina: 'Tópicos Especiais em Transportes I',
    codigo: 'FEN02-03668',
    periodo: '-',
    conflito: false,
    trava: 170,
    prereq: false,
    type: 'Disciplinas Eletivas Definidas',
  },
];
